### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RapidRob** [allspiritseve/selene#8]
Greetings,
I am getting an Error when trying to parse a couple of iCal events that pass validation elsewhere.

parsing feed: ParseError
Could not parse ical, possibly invalid.

The files were generated by Google  calendar.

[iCal_parse_error.zip](https://github.com/allspiritseve/selene/files/2871266/iCal_parse_error.zip)

**Comment by allspiritseve** [comment]
Hi, it looks like those files were raising `ArgumentError: invalid byte sequence in UTF-8`. I just pushed a new version that hopefully resolves it.

**Comment by RapidRob** [comment]
Still choking... 
those  iCal files are all located in
https://www.bmca.com/calendar/iCal-events-2019-tours/

List:
Adriatic_Amble.ics
Alpine_Adventure_East.ics
Alpine_Adventure_West.ics
Classic_Alpine_Adventure_Aug.ics
Classic_Alpine_Adventure_July.ics
Dolomite_Domination.ics
Island_Interlude.ics
Italian_Idyll.ics
Maori_Meander.ics
Swiss_Splendor.ics

I am hoping to be able to generate the ics from work already done in Google Cal. and then using your JSON output to add microdata to the individual tour web pages on our site.... but again I am seeing the same error when using the parser online.

**Comment by allspiritseve** [comment]
Perhaps you are using the [demo app](ical-to-json.herokuapp.com)? I had only updated the gem.

Demo app is now updated to use the latest version.

**Comment by RapidRob** [comment]
Bingo... that was it, as I only have to convert those few files, I didn't run it locally, I was testing with the demo.

Demo now working perfectly. Thank you for your update.

**Comment by allspiritseve** [comment]
You’re welcome.
